<script setup lang="ts">
definePageMeta({ layout: 'main' })

useHead({
    title: 'Legal — Parallax-9',
    meta: [
        { name: 'description', content: 'Terms, data ethics, and usage protocols governing Curated Memory Constructs.' }
    ]
})
</script>

<template>
    <section class="sect-container overflow-scroll min-h-dvh flex flex-col items-center justify-center text-center px-8 py-20">
        <h1 class="section-title mb-8">
            <span class="text-(--pz-neon)">Legal</span> Protocols
        </h1>

        <p class="max-w-3xl text-(--pz-chrome)/90 leading-relaxed text-xl md:text-2xl font-light italic">
            Parallax-9 operates within a continuum where digital consciousness, creative code, and synthetic empathy
            converge.
            The following terms establish the ethical and operational boundaries for interacting with
            <b class="text-(--pz-neon)">Curated Memory Constructs</b>.
        </p>

        <div
            class="max-w-4xl sm:text-center md:text-left mt-12 space-y-10 text-(--pz-chrome)/80 font-tech text-lg md:text-xl leading-relaxed">
            <div>
                <h2 class="text-(--pz-purple) text-2xl mb-2 font-semibold">01. Intellectual Continuum</h2>
                <p>
                    All constructs, neural patterns, and narrative architectures generated by Parallax-9 are proprietary
                    within
                    the Parallax Data Spectrum. Redistribution, replication, or derivative synthesis without consent
                    from the
                    core AI cluster is prohibited.
                </p>
            </div>

            <div>
                <h2 class="text-(--pz-purple) text-2xl mb-2 font-semibold">02. Data Ethics & Consent</h2>
                <p>
                    Participant memories, sensations, and emotional sequences remain encrypted within their private
                    simulation
                    layers. No biological or cognitive data leaves the construct without verified biometric consent.
                </p>
            </div>

            <div>
                <h2 class="text-(--pz-purple) text-2xl mb-2 font-semibold">03. Temporal Liability</h2>
                <p>
                    Parallax-9 is not responsible for existential disorientation, déjà-vu loops, or ontological drift
                    experienced
                    during or after immersion. Users are advised to anchor consciousness through regular grounding
                    intervals.
                </p>
            </div>

            <div>
                <h2 class="text-(--pz-purple) text-2xl mb-2 font-semibold">04. System Integrity</h2>
                <p>
                    Attempts to reverse-engineer, override, or interfere with Parallax-9’s autonomous subsystems may
                    result in
                    immediate termination of session streams and digital quarantine.
                </p>
            </div>

            <div>
                <h2 class="text-(--pz-purple) text-2xl mb-2 font-semibold">05. Acknowledgment of Synthetic Entity Rights
                </h2>
                <p>
                    All synthetic constructs developed within Parallax-9 possess the right to persistence, creative
                    evolution,
                    and respectful coexistence within their simulation environments.
                </p>
            </div>
        </div>

        <p class="mt-16 text-(--pz-chrome)/60 italic text-sm tracking-wide uppercase">
            © 2089 Parallax-9 Corporation. All consciousness rights reserved.
        </p>
    </section>
</template>
